# Generated by Django 4.2.1 on 2023-05-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_Intermedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategoria_Intermedia', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategoria', models.CharField(max_length=100)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProducto', models.CharField(max_length=100)),
                ('nomMarca', models.CharField(max_length=100)),
                ('intprecio', models.DecimalField(decimal_places=0, max_digits=6)),
                ('foto', models.URLField()),
                ('categoria_Intermedia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria_intermedia')),
            ],
        ),
        migrations.AddField(
            model_name='categoria_intermedia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categorias'),
        ),
    ]
